### ISSUE TITLE
Implement smart basis selection in guided mode

### ISSUE THREAD

**Issue by pjknowles** [molpro/iMolpro#106]
As in gmolpro

- [x] quality selector
- [x] quality-filtered QComboBox of default basis sets
- [x] Element-specific basis pop-out dialogue

**Comment by pjknowles** [comment]
Needs https://github.com/molpro/iMolpro/issues/110

**Comment by pjknowles** [comment]
@klauspdoll is https://github.com/molpro/iMolpro/pull/115 enough for getting what's needed from the basis library?

**Comment by klauspdoll** [comment]
I have tried to use it with these changes (from https://github.com/molpro/iMolpro/pull/115 , modified)

```
diff --git a/ProjectWindow.py b/ProjectWindow.py
index 65c03d0..f4a6d4a 100644
--- a/ProjectWindow.py
+++ b/ProjectWindow.py
@@ -8,2 +8,4 @@ import sys
 import re
+import pymolpro
+from defbas import Defbas
 
@@ -487,2 +489,9 @@ class ProjectWindow(QMainWindow):
 
+        p = pymolpro.Project(str('/tmp/test.molpro'))
+        defbas = Defbas(p.local_molpro_root())
+        if defbas is not None:
+            assert defbas.contents
+
+        assert len(defbas.search('Ne', 'vdz')) == 1
+
     def refresh_guided_pane(self):

```

Now it says after start:

```
    defbas = Defbas(p.local_molpro_root())
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Project' object has no attribute 'local_molpro_root'

```

**Comment by pjknowles** [comment]
Need to update pymolpro/pysjef dependencies: `conda install -y --file requirements.txt`

**Comment by pjknowles** [comment]
Let's try to specify what the logic should be.

1. At the start, we expect to have `input_specification['basis']` containing `default`, `quality` and `elements`.  If missing, set to a default value, perhaps `default=cc-pVTZ-PP`.
2. At the start, we expect `input_specification['hamiltonian']` to contain one of `molpro_input.hamiltonian.keys()`. If it doesn't, set it to a default value, derived from the basis set (whether default contains `-PP`) and (implementation later) whether DK is in the input.
3. Populate the basis combo with those basis sets in the molpro registry that are compatible with quality and hamiltonian, plus a null entry. If `input_specification['basis']` exactly matches one of these, and `input_specification['basis']['elements']` is empty, select that basis, otherwise select the null entry.
4. The action from the basis combo should, if anything other than the null entry has been selected, be to set `input_specification['basis']`. There shouldn't be any need for a consequential change of hamiltonian, since the list of basis sets is already filtered by the hamiltonian.
5. The action from the hamiltonian selector should be to set `input_specification['hamiltonian'], unset `input_specification['basis']` and return to the top. There are doubtless some complicated paths possible whereby the basis does not need to be forgotten, but maybe hard to code in a safe way.
6. The action from the quality selector should be similar to hamiltonian, except that the basis should not be reset if the quality is not changing, or if the quality has been set to all.

**Comment by pjknowles** [comment]
The remaining thing left to do here is support for element-specific basis sets. However, as things stand, it is possible to type these in the input by hand yet still remain in guided mode, without the element basis sets being overwritten unless a new basis set is chosen. Therefore I think this issue can be dropped from the list to be done before a first release, https://github.com/molpro/iMolpro/milestone/1 , but left as a future possible enhancement. @klauspdoll , @hjwerner  OK with this?

**Comment by hjwerner** [comment]
Unfortunately I had introduced bugs when changing the defbas stuff. Hopefully better now with MR #4347

**Comment by klauspdoll** [comment]
Yes, certainly OK with me to drop this from the milestone list.

I am however struggling with entering a general basis set, and remaining in guided mode. This may be a separate issue.

E.g. this does not allow guided mode:

```
basis={
default=cc-pV(T+d)Z-PP
be=def2-svp
}

```
A block with `basis ...  end` is possible:  if I start from guided mode without basis set, then insert this:

```
basis
default=cc-pV(T+d)Z-PP
be=def2-svp
end

```
But when I click on guided mode, it crashes, see issue #199 .

**Comment by pjknowles** [comment]
You can at the moment do it with `basis,cc-pV(T+d)Z-pp,be=def2-svp` and this was the form that we agreed in a meeting that we would support for guided mode.
Until #199 is fixed, you can use
```
basis={
default=cc-pV(T+d)Z-PP
be=def2-svp
}
```
but it won't go into guided mode.

**Comment by klauspdoll** [comment]
> You can at the moment do it with `basis,cc-pV(T+d)Z-pp,be=def2-svp` and this was the form that we agreed in a meeting that we would support for guided mode. 

OK, great, works. And `= instead of ,`  ,i.e. `basis=cc-pV(T+d)Z-PP,be=def2-svp` also works.

**Comment by pjknowles** [comment]
... and you should be able to see that the parsing, and writing back, of this input form is already done:
```
{
  'steps': [{'command': 'rhf'}],
  'geometry': 'be\nh,be,r\nh,be,r,h,theta',
  'basis': {'default': 'cc-pV(T+d)Z-pp',
  'elements': {'Be': 'def2-svp'}},
  'density_fitting': True,
  'variables': {'r': '1 angstrom',
  ' theta': '110',
  'charge': '0'},
  'hamiltonian': 'AE'
}
```
so all that really remains is setting up a dialogue in `ProjectWindow` to edit the element-specific part.

**Comment by pjknowles** [comment]
This was completed with https://github.com/molpro/iMolpro/pull/249 . In principle one might do more for mixed core, but this needs more support from Molpro registry probably: https://github.com/molpro/iMolpro/issues/250
