### ISSUE TITLE
Tidy the layout of guided pane

### ISSUE THREAD

**Issue by pjknowles** [molpro/iMolpro#107]

**Comment by pjknowles** [comment]
As well as making the run-time layout looking like gmolpro, the code should be given more structure to improve its maintainability. It probably starts with carving off everything for guided pane to a separate class or function.  I'm happy to do it all, but it should not be done whilst there is active progress on the guided functions themselves. @klauspdoll can I pick this up over the weekend?

**Comment by klauspdoll** [comment]
I try to finish the default basis set today, then you can do the changes you plan to do. I'll let you know how things progress.

**Comment by pjknowles** [comment]
Most functions are now done, but there could be further style improvements
