### ISSUE TITLE
More flexible job control

### ISSUE THREAD

**Issue by hjwerner** [molpro/iMolpro#111]
Implement choice of system, number of cores etc. Add kill button and job repeat buttons, just as in gmolpro

**Comment by pjknowles** [comment]
I think this is all done already. Look in the menus. But maybe something is missing?

**Comment by hjwerner** [comment]
Ah, it’s in the top menus. I expected it near the run button as in gmolpro.

**Comment by pjknowles** [comment]
We can discuss what should show always as a button. It seemed to me that 'kill' and 'run (force)' were things that you would need only exceptionally, and wouldn't want to activate accidentally. 'Backend' is however a candidate for a button.

**Comment by pjknowles** [comment]
@hjwerner you can try this with https://github.com/molpro/iMolpro/releases/tag/0.3.25 . Please reopen if you think it could be improved further.

**Comment by hjwerner** [comment]
This version (0.3.25) crashes when I try to open an existing project - and if one tries to make a new one as well.

**Comment by pjknowles** [comment]
Ouch, so it does. I will look for the problem.
