### ISSUE TITLE
No input seen in guided mode

### ISSUE THREAD

**Issue by hjwerner** [molpro/iMolpro#112]
When I create a new project or open a new one in guided mode I see no input. Also it is not immediately intuitive how to import a structure. Maybe add a button as in gmolpro? Prevent run submission if no geometry is found?

This applies to version iMolpro-0.3.23.Darwin.arm64.

**Comment by pjknowles** [comment]
> Prevent run submission if no geometry is found

Yes. Split this off as a separate issue.

**Comment by pjknowles** [comment]
> Also it is not immediately intuitive how to import a structure. Maybe add a button as in gmolpro? 

It's in the menus. We can discuss how many of these menu functions should appear as explicit buttons, but there is a good case for making this one more prominent when there is not yet any geometry.

**Comment by pjknowles** [comment]
> When I create a new project or open a new one in guided mode I see no input.

I'm not sure I understand what is not seen. With a new project, it should open in guided mode, and you can switch to freehand by switching tab (or apple-g).
<img width="374" alt="Screenshot 2023-11-22 at 16 31 57" src="https://github.com/molpro/iMolpro/assets/1985232/0d907f4a-68bc-4f48-a316-0baf903384f1">
<img width="376" alt="Screenshot 2023-11-22 at 16 32 21" src="https://github.com/molpro/iMolpro/assets/1985232/fadebda0-bce1-42b4-989f-56ac818a1f39">
If this isn't seen on a new project, then we should look for a bug.

**Comment by pjknowles** [comment]
> It's in the menus. We can discuss how many of these menu functions should appear as explicit buttons, but there is a good case for making this one more prominent when there is not yet any geometry.

Probably the best thing is to put a button on guided mode `Import geometry`.

**Comment by hjwerner** [comment]
I see only this (screenshot attached). It does not change if a geometry is loaded. Even if this shows everything that defines the job, I would like to see the input (and perhaps modify it).

**Comment by hjwerner** [comment]
I don’t see the second one.

**Comment by pjknowles** [comment]
You mean that you do not see 'freehand' or cannot click on it?

**Comment by hjwerner** [comment]
Under freehand I see the input. I also expected to see it in guided mode.

I just noticed that it generates for example

geometry=c2h4.xyz
basis={default=cc-pVTZ-PP}
QCISD(T)
optg

Is it correct that there is no HF?

**Comment by pjknowles** [comment]
> Under freehand I see the input. I also expected to see it in guided mode.

Saves screen space. You can easily switch between them with apple-g.

**Comment by pjknowles** [comment]
> I just noticed that it generates for example geometry=c2h4.xyz basis={default=cc-pVTZ-PP} QCISD(T) optg Is it correct that there is no HF?

The logic for adding this needs to be coded up.

**Comment by pjknowles** [comment]
> > Under freehand I see the input. I also expected to see it in guided mode.
> 
> Saves screen space. You can easily switch between them with apple-g.

If you really must see both on the screen simultaneously, you can open another instance of the project (File/Open, then select the project again). Edits made on guided pane will be reflected immediately in the input; for efficiency reasons, edits in input will not immediately result in a change on the guided pane.

**Comment by pjknowles** [comment]
da84ccbaef0041e331eba01732f3be994b7c81b2 shows the input in the right-hand viewing pane.
