### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by pjknowles** [molpro/iMolpro#12]
Create documentation and link to it from the Chooser and menu bar

**Comment by pjknowles** [comment]
Basic introduction is done, and sjef backends, but maybe more can be added

**Comment by pjknowles** [comment]
@klauspdoll do you think the documentation is by now adequate, or is there something missing that we need to describe? Most people don't want to read documentation, but if there is something that is not obvious without description - for example sjef backends - we should describe it.

**Comment by klauspdoll** [comment]
I think it is a bit abstract; maybe one example of the workflow would be good;
like : start the program like this, get a structure from here, set up an input like that, run, look at properties

**Comment by pjknowles** [comment]
It's done, but will need revising (at least updated graphics in example) when #11 is complete.

**Comment by klauspdoll** [comment]
I think it might be good to have a screenshot here also

https://github.com/molpro/iMolpro/tree/master#imolpro

i.e. where it says

"On launching, you will normally see the Chooser window that allows you to open or create projects. You can have as many open as you want, and each appears in its own independent project window. Each project window has two principal panes: on the left is the job input, either as the actual Molpro input file or via a menu-driven guided input creator; on the right is the job output and/or the three-dimensional molecular structure together with any orbitals or vibrational modes that have been calculated, and an editable three-dimensional model of the input geometry."

one could perhaps shorten the text, and have one or two screenshots.

**Comment by pjknowles** [comment]
The example images appear in `doc/example.md`. Rather than making `README.md` longer, I'll put a link in to `doc/example.md`.
