### ISSUE TITLE
non-reproducible:   'Projects' 'File' pulldown not properly working

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#125]
I have some cases where the pulldown `Projects` and `File` do not work upon click. Edit works however, and when clicking Edit and then moving the mouse to File or Projects, then the pulldown menus appear.

**Comment by pjknowles** [comment]
Should be fixed with sjef 1.37.5

**Comment by pjknowles** [comment]
@klauspdoll can you please either provide a bit more evidence for this, or close if you think the problem is no longer there?

**Comment by klauspdoll** [comment]
I does not happen any more, so I close this.
