### ISSUE TITLE
A list of HJW' comments (to be deleted later)

### ISSUE THREAD

**Issue by hjwerner** [molpro/iMolpro#158]
- [x] Installation: Activation and access to "Downloads" required? 
- [x] Default basis set vtz-pp (or avtz-pp?) should be set.
- [x] Chosen basis set is not shown after reopening a project.
- [x] Charge and spin of the molecule should be shown (default or chosen), also after re-opening a project #156
- [x] How to get orbital plots? Clicking orbital plot of canonical and/or PM has no effect. 
- [x] Run button is not re-activated if the input changes (e.g. a different basis set).
- [x] Options for localized orbitals and properties should be added.
- [x] What an about of options for different program steps as in gMolpro? #165
- [x] Setting charge=1 has no effect.
- [x] Properties should be added

**Comment by pjknowles** [comment]
> Run button is not re-activated if the input changes (e.g. a different basis set).
> 
> Setting charge=1 has no effect.

These ones I think were the consequence of a regression I introduced yesterday, which I have just fixed. Updated binaries are at https://github.com/molpro/iMolpro/releases

**Comment by hjwerner** [comment]
Ah, I now found that my comments are under issues and not Milestones. Sorry. But in the mail I just sent were some additional comments.

**Comment by hjwerner** [comment]
Thanks, now works!

**Comment by pjknowles** [comment]
> Default basis set vtz-pp (or avtz-pp?) should be set.

Isn't this already the case?

**Comment by pjknowles** [comment]
> Charge and spin of the molecule should be shown (default or chosen), also after re-opening a project

This is #156 and needs a discussion

**Comment by hjwerner** [comment]
It wasn’t the case in 0.3.39 but now works in 40.

**Comment by hjwerner** [comment]
But the default quality seems not to be remembered.

**Comment by pjknowles** [comment]
All have been done or captured in separate issues
