### ISSUE TITLE
Decide on a good name for this program

### ISSUE THREAD

**Issue by pjknowles** [molpro/iMolpro#17]
`QtMolpro` is perhaps not the best - nobody really cares that it's implemented with Qt. `gmolpro` is already taken. `imolpro` to emphasis _interactive_? `xmolpro` as a pointer towards X Window as used on linux?

**Comment by pjknowles** [comment]
Changed to Molpro

**Comment by pjknowles** [comment]
@hjwerner says: gmolpro and molpro have the same Molpro symbol on Mac. Maybe change one (e.g. a „g“ under the M for gmolpro? Or an „i“ for interactive Molpro?)

This reopens the question of what we should call this program, and how it should look. I had thought that just 'Molpro' is best because most people using it will not be aware that there are two possibilities. But we should discuss and get it right.

**Comment by hjwerner** [comment]
I wouldn’t call it both the same. We still want to have the old molpro, and there should be no confusion in the linux PATH.
Maybe the interactive one iMolpro? (unless „i“ is protected by Apple).

**Comment by pjknowles** [comment]
One has to think that someone using this front end probably wants to think only of one program, not two, and therefore this speaks in favour of the GUI being called 'Molpro'.  The conflict with the backend I don't think exists - on linux, file names are case-sensitive, and on macOS you wouldn't launch it from the command line normally.

However we have to balance this against confusion with gmolpro, and maybe iMolpro is a good idea.

As far as the icon is concerned, I would leave it as it is. In the unlikely event that someone is running gmolpro as well, they can still see the name when they do apple-tab or similar.

I don't think Apple yet own 1/26 of the alphabet.

**Comment by hjwerner** [comment]
But one has also to think that there are many previous users of Molpro who like molpro and who might want to continue using it in the old way (and perhaps QtMolpro as well, depending on the case). I think having molpro and Molpro is confusing. It would be better to have a separate name for the front-end. 

With the icon, it is not so nice that it looks as in the attachment, even though one can see what is what by moving the mouse over it.

**Comment by pjknowles** [comment]
> But one has also to think that there are many previous users of Molpro who like molpro and who might want to continue using it in the old way (and perhaps QtMolpro as well, depending on the case). I think having molpro and Molpro is confusing. It would be better to have a separate name for the front-end.

Yes, that's a fair point. `iMolpro` but perhaps discuss at next meeting?

**Comment by hjwerner** [comment]
Yes, let’s discuss it on Thursday (if I can attend, which I don’t know now yet). I quite like iMolpro, but I am not sure if this is a good name for Linux and windows.

**Comment by pjknowles** [comment]
Changed to iMolpro with https://github.com/molpro/iMolpro/commit/fdb4876a354f6a0b9ccdd83a0959a233be322b49
