### ISSUE TITLE
Provide option specification for HF preceding a correlation method

### ISSUE THREAD

**Issue by pjknowles** [molpro/iMolpro#180]
Yes, as in gmolproVon meinem iPhone gesendetAm 02.01.2024 um 08:22 schrieb Peter Knowles ***@***.***>:﻿

3.) I do not see how to select options for the reference function.

You mean specifying options for the Hartree-Fock preceding a correlated method?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

_Originally posted by @hjwerner in https://github.com/molpro/iMolpro/issues/179#issuecomment-1873937965_

**Comment by pjknowles** [comment]
Probably what is needed is a set of options for each of Hartree-Fock, correlation method, geometry optimisation, frequencies.  In the case of frequencies, `thermo` should always be specified, and some of the options transferred to/from it when the input is written/read (see https://www.molpro.net/manual/doku.php?id=harmonic_vibrational_frequencies_frequencies#thermodynamical_properties_thermo)  .. so that the enthalpy and Gibbs energy can be reported in iMolpro.

The simplest way to achieve this might be to reorganise the data model for the input to contain something like
```
{methods={
  'hf' : {'short_name': 'HF', 'name' : 'Hartree-Fock', 'options' : {'shiftc' : '.1', 'shifto' : '.2'}},
  'mp2' : {},
  'optg' : {'short_name': 'Optimise', 'name': 'Geometry optimisation'},
  'frequencies' : {'options' : {'temp' : 298, 'analytical: ''}},
}
```
and then provide a button to set these options for each of the entries in `methods`.
This will result in a decrease, rather than increase, in the complexity of the logic. We can rely on the ordering of dictionary entries not changing, which is true since python 3.7.

**Comment by hjwerner** [comment]
Exactly!Von meinem iPhone gesendetAm 03.01.2024 um 18:24 schrieb Peter Knowles ***@***.***>:﻿
Probably what is needed is a set of options for each of Hartree-Fock, correlation method, geometry optimisation, frequencies.  In the case of frequencies, thermo should always be specified, and some of the options transferred to/from it when the input is written/read (see https://www.molpro.net/manual/doku.php?id=harmonic_vibrational_frequencies_frequencies#thermodynamical_properties_thermo)  .. so that the enthalpy and Gibbs energy can be reported in iMolpro.

**Comment by pjknowles** [comment]
Then I'll do it this way, and we can see how we like it.

**Comment by pjknowles** [comment]
For further consideration: if you want to calculate the enthalpy, then this can be quite conveniently done with a stripped version of G4 or similar, which looks something like
```
basis,vtz
ks,b3lyp
optg
frequencies
basis,cc-pvqz-f12
ccsd(t)-f12
```
This can be accommodated with the suggested structure, except for the use of two basis sets.  We might not want to do this now, but it's best to think of all things like this before settling on a change to the data logic.

**Comment by pjknowles** [comment]
Completed with #183
