### ISSUE TITLE
crash when opening project, non-reproducible, Argument list too long: '/bin/sh'

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#190]
version 5c2f08605147

again non-reproducible:

while opening this input:

```
geometry={
o
}
basis=cc-pV(T+d)Z-PP
charge=1
{

}


```
```
  File "/home/doll/imolpro/iMolpro/Chooser.py", line 148, in action
    self.parent.window_manager.register(ProjectWindow(self.filename, self.parent.window_manager))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doll/imolpro/iMolpro/ProjectWindow.py", line 134, in __init__
    os.environ['PATH'] = os.popen(os.environ['SHELL'] + " -l -c 'echo $PATH'").read() + ':' + os.environ[
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 993, in popen
  File "/home/doll/miniconda3/envs/iMolpro/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/doll/miniconda3/envs/iMolpro/lib/python3.12/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/bin/sh'

[1]+  Aborted                 (core dumped) python iMolpro.py

```

also non-reproducible: sometimes local molpro cannot be found in this context

**Comment by klauspdoll** [comment]
Seen again:

First, it cannot find local molpro.

When I close and reopen the same project, then it crashes with the message above.

**Comment by pjknowles** [comment]
On my linux system,
```
peterk@thanos:~$ /bin/bash -c '/bin/true $(seq 1 147016)'
peterk@thanos:~$ /bin/bash -c '/bin/true $(seq 1 147017)'
/bin/bash: line 1: /bin/true: Argument list too long
```
What about on yours, @klauspdoll ? What is the length of `$PATH`? What shell are you using?

**Comment by pjknowles** [comment]
If you can reproduce with #192, then we might see more in the error message that it pops up.

**Comment by klauspdoll** [comment]
> On my linux system,
> 
> ```
> peterk@thanos:~$ /bin/bash -c '/bin/true $(seq 1 147016)'
> peterk@thanos:~$ /bin/bash -c '/bin/true $(seq 1 147017)'
> /bin/bash: line 1: /bin/true: Argument list too long
> ```
> 
> What about on yours, @klauspdoll ? What is the length of `$PATH`? What shell are you using?

I use bash and have:

```
/bin/bash -c '/bin/true $(seq 1 146859)'
/bin/bash -c '/bin/true $(seq 1 146860)'
/bin/bash: /bin/true: Argument list too long

echo $PATH |wc
      1       1     924

echo $SHELL
/bin/bash

```

**Comment by pjknowles** [comment]
OK, so nothing obvious from a huge $PATH. And if you use #192, what error message?

**Comment by klauspdoll** [comment]
I have tried a couple of times now, but no failure....

I vaguely remember that yesterday it was when I created a new project, then no geometry imported...

But not reproducible. I'll keep trying ...

**Comment by klauspdoll** [comment]
This below is NOT what I did yesterday (and not a case to trap as it is something one should not do), but to get any error at all I did this:

I have now tampered with my Molpro installation, and, first make molpro unusable (i.e. remove from path)

1 ) `mv ~/bin/molpro ~/bin/molpro_sicher`

2 ) `python iMolpro.py`

3 ) open project, close project etc, gives correctly error message that molpro is not found

4 ) make Molpro usable

`mv ~/bin/molpro_sicher ~/bin/molpro`

now Molpro works again, and I have **non-reproducibly** (rarely !):

5 ) open project

`[Errno 7] Argument list too long: '/bin/sh'`

![Screenshot_20240112_111753](https://github.com/molpro/iMolpro/assets/109160884/86d31648-337d-41d7-bf4a-c5bf99c5258c)

**Comment by pjknowles** [comment]
Thanks. So unfortunately we don't get any more information from the pop-up, but at least it doesn't crash. I'll merge in that change, even though we haven't yet found the problem.

**Comment by klauspdoll** [comment]
I have now a hint how to obtain this.

Long suggestion (how it occurred):

Create a new project `$HOME/imolpro/bla7.molpro`
Erase it, it goes to `$HOME/.molpro/iMolpro.trash/bla8.molpro`
Click on the erased project` $HOME/.molpro/iMolpro.trash/bla8.molpro` to be opened, it however behaves as if "New project " had been clicked. Erase  it again, it goes to `$HOME/iMolpro.trash/bla8.molpro` (different path. why !?)
Create new project in `$HOME/imolpro/bla8.molpro`
Erase it.
Now open `$HOME/.molpro/iMolpro.trash/bla8.molpro` : Error in finding local  molpro

This is somewhat unrealistic, but perhaps a hint can be deduced where the error comes from.
E.g. is there a problem when there is a dot-file like .molpro in the path or so?

Also seen (non-reproducible):

`QObject::startTimer: Timers cannot be started from another thread`

**Short:**
create a project with name .bla9 (leading dot) then you may hit this error (perhaps it has to be in some dot-directory like `$HOME/.molpro/iMolpro.trash/  )

Also sometimes seen when clicking on a project such as
`$HOME/.molpro/iMolpro.trash/bla3.molpro` (after deleting a project, it appears in the project list though it is in the trash-folder, until Quit is done and python iMolpro.py freshly started)

**Comment by pjknowles** [comment]
I am beginning to suspect that this trouble comes only when you try to reopen a project that has been renamed (including moving to `iMolpro.trash`), and iMolpro is still running.  Python objects do not get deleted when you delete the last reference to them, and maybe some chaos arises with multiple openings of the same project.  Trash has now been reimplemented using the safer `pysjef.Project.trash()`. Does the problem still exist if you just use the code in an ordinary way?

**Comment by klauspdoll** [comment]
When I create a new project and then erase it, I now get this error:

```
python iMolpro.py 
Traceback (most recent call last):
  File "/home/linux24_i1/doll/imolpro/iMolpro/ProjectWindow.py", line 1030, in erase
    self.project.trash()
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'Project' object has no attribute 'trash'. Did you mean: 'erase'?
Aborted (core dumped)

```
seen with 7ebe40236339

**Comment by pjknowles** [comment]
Do you really see this with the correct environment? The requirements have changed.

**Comment by pjknowles** [comment]
> Do you really see this with the correct environment? The requirements have changed.

As usual, `conda install -y -c conda-forge --file requirements.txt`

**Comment by klauspdoll** [comment]
I thought I had done  `conda install -y -c conda-forge --file requirements.txt` , but have done it again now. Anyway, now it works. Perhaps just close this issue; if it ever returns, a new issue may be opened.
