### ISSUE TITLE
error on startup: invalid escape sequence '\d'

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#217]
version 618638f9c:

upon startup:

`python iMolpro.py`

```
imolpro/iMolpro/molpro_input.py:675: SyntaxWarning: invalid escape sequence '\d'
  result = re.sub('(dkho=\d)\n(geomtyp=xyz)', '\\2\n\\1', result, flags=re.MULTILINE|re.IGNORECASE)

```
The error is not displayed when you once again start `python iMolpro.py `. However, if you a change the code (e.g. insert a blank line on top of `molpro_input.py`) and start, then you see the error again.

**Comment by pjknowles** [comment]
It's a bug. The first string is not raw, and so it should be `\\d`. I'll fix it.
