### ISSUE TITLE
change in basis set line; "warning should not happen" (some untrapped case I guess)

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#222]
I reused an old input which looks like this:

```
orient,mass;
nosym;
geometry=opt-test.xyz
basis=def2-SVP

{DF-RKS,LDA}
{OPTG}

```
while I edit this (I hit return after `basis=`)
```
basis=
def2-SVP

```
then an error is printed in the terminal:

`** warning should not happen`

**Comment by pjknowles** [comment]
This simply needs to be condoned, and an unsuccessful parse returned.
