### ISSUE TITLE
Display size varies and structure not shown when a project is loaded

### ISSUE THREAD

**Issue by hjwerner** [molpro/iMolpro#229]
As noted earlier, it would be nice if the geometry would immediately displayed when a project is loaded. Currently one has to open the project, then click view -  initial structure, then initial structure below the window.

When one makes a new project and loads the structure (using the initial pop up) the shown window with the molecule is very small.  This does not happen of one loads the structure using files -import structure, or when opening an existing project as described above. See screen shots attached.

![Bildschirmfoto 2024-07-31 um 16 44 39](https://github.com/user-attachments/assets/228c281d-7815-435f-bde3-0165f4139364)
![Bildschirmfoto 2024-07-31 um 16 44 00](https://github.com/user-attachments/assets/d6d1f970-859a-43d4-a664-255ac887c7f5)

When loading some large molecules, I had some crashes (errors loading the structure), but cannot reproduce this yet. I'll make an issue when I see it again in a reproducible way.

**Comment by pjknowles** [comment]
What is described amounts to the builder not filling the space that it could.

**Comment by pjknowles** [comment]
... and this is because in `embedded_vod()` the geometry of the output tabs is used to set the size, but if there are no outputs yet, this doesn't work in `embedded_builder()`. Need to find a way to proxy this calculation.

**Comment by pjknowles** [comment]
Also wanted is that when there is a structure, it is always shown. I am not so sure about this. It seems to me that if there is already an output file, that should be shown as the active tab.

**Comment by pjknowles** [comment]
@hjwerner please try, and reopen if you think it could still be improved.

**Comment by hjwerner** [comment]
I confirm that now the structure appears immediately when opening a project. But the default window is too small for viewing large molecules. I found (by chance) that command D increases it (then it’s nice!). This is in the „Edit“ menu „Structure“. I don’t find this intuitive. How does one get out of this mode? Maybe make the large one the default? But perhaps this would not work with a low-resolution screen.

Further suggestions:

 - Have a button „Labels“ below the window (next to „Builder in the grey bar): This should activate/deactivate „Style - Labels - With Atom names"
 - Change the default color for labels to black: „Color - Labels - black“ 
   (with the default some labels are grey and cannot be clearly seen on C-atoms)
 - How to get out of full-screen mode? Escape does not do it.
 - View Zoom in or Zoom out do not work for me. Also the short-cut option/shift/= for zoom in is inconvenient. 
   Could it not simply be command +/- for in and out?
 - What is the difference of zoom in/out in the View and Edit menus? Both do nothing for me.

 
For the input builder, a generalisation of the basis selector is in my view most important. As far as I see, there is so far no possibility to generate, e.g., basis,avtz,h=vtz, or, basis=avtz,h=vtz, Fe=awcvtz.

It seems to me that iMolpro and gMolpro projects are not compatible. This is a pity, but I guess hard to fix. But if so, maybe the project names should be different, e.g. h2o.imolpro and h2o.gmolpro?
