### ISSUE TITLE
iMolpro_thresh files should not be shown in recent projects

### ISSUE THREAD

**Issue by hjwerner** [molpro/iMolpro#230]
When one erases a project, the current default directory (e.g. for saving the next new project) changes to iMolpro_trash. This is undesired and confusing. Also, the projects in iMolpro_trash are shown in recent projects. This is also disturbing and should be avoided. If one really wants to recover a projects from the trash one could select the trash directory explicitly (of course then showing the contents).

**Comment by pjknowles** [comment]
After https://github.com/molpro/iMolpro/commit/e3a49ce80cacb112bcddde8c34371ecf41db77f8 , trashed projects no longer appear in the recent project list. As far as I can tell from testing, it is also no longer the case that the trash directory becomes the default for opening a new project.
