### ISSUE TITLE
wrong behaviour when clicking an existing project that has not run

### ISSUE THREAD

**Issue by hjwerner** [molpro/iMolpro#232]
I created a project just to look at the structure and then closed it. Then I tried to open it again by clicking its name in "Recent projects". This does not work properly, it asks again whether I want to import a structure rather than using the uploaded one.

The problem seems to disappear once one has opened it again via the file menu (or maybe a race problem?)

**Comment by pjknowles** [comment]
I can't reproduce this. What I tried: new project; don't get geometry from a file; get water from pubchem; close the project; open it from the recent project list. It opens fine, but it does not show the structure even though the xyz file is in the project and referenced from the input.
