### ISSUE TITLE
Redirection of stdout and stderr

### ISSUE THREAD

**Issue by cchembio** [molpro/iMolpro#262]
While the log file path is dependent on TMPDIR, TMP,... variables, the stdout and stderr are forcibly placed at /tmp/st...

This is an issue for more than one local instance running in a machine. It would be a quick fix to just use the same structure as for the log file. Not sure why this wasn't done, perhaps there is a good reason.

**Comment by pjknowles** [comment]
There was no reason for `/tmp`, just historical. In principle there needn't be more than one instance running, and if there is, there's no guarantee they won't have the same `$TMPDIR`, but `stdout` and `stderr` are kept only for debugging purposes, so none of this should really matter.
