### ISSUE TITLE
describe prerequisites for running/developing directly from a git clone

### ISSUE THREAD

**Issue by ajmay81** [molpro/iMolpro#31]
At some point before this worked:
```
conda create -c conda-forge -n QtMolpro 'pymolpro>=1.3.32' pyqt=5 -y
conda activate QtMolpro
```
then I needed to add:
```
conda install -y -c conda-forge pyqtwebengine
```
and now it seems more is needed:
```
> python Molpro.py                
Traceback (most recent call last):
  File "/host/Molpro.py", line 4, in <module>
    from Chooser import Chooser
  File "/host/Chooser.py", line 17, in <module>
    from ProjectWindow import ProjectWindow
  File "/host/ProjectWindow.py", line 16, in <module>
    from database import database_choose_structure
  File "/host/database.py", line 4, in <module>
    import pubchempy
ModuleNotFoundError: No module named 'pubchempy'
```
It would be great if somewhere in the `README` or an `INSTALL` file there would be a concise list of what is needed from a fresh conda install to run and develop with the app.

**Comment by pjknowles** [comment]
Look in `build.sh` for the needed conda environment. It should be moved into a `requirements.txt`, of course.

**Comment by pjknowles** [comment]
`conda install -c conda-forge -y --file=requirements.txt`

and

`cat INSTALL`

**Comment by ajmay81** [comment]
Thanks, this works, but it takes a very long time at this stage:
```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: ...working... unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
```
Is there some way to avoid the unsuccessful stages? Here is a Dockerfile to reproduce:
```
FROM opensuse/leap:15.5

RUN zypper in -y curl which

RUN export MINICONDA="Miniconda3-latest-Linux-x86_64.sh" && \
    curl -LsO https://repo.anaconda.com/miniconda/${MINICONDA} && \
    chmod +x ${MINICONDA} && ./${MINICONDA} -b && \
    . ${HOME}/miniconda3/bin/activate && conda init && \
    conda update -n base -c defaults conda -y && \
    rm ${MINICONDA}

RUN . ~/.bashrc && \
    curl -LsO https://raw.githubusercontent.com/molpro/QtMolpro/master/requirements.txt && \
    conda install -y -c conda-forge --file=requirements.txt && \
    rm requirements.txt
```

**Comment by pjknowles** [comment]
If you're in a hurry, first install mamba into the environment, then use it instead of conda.

**Comment by ajmay81** [comment]
I'll look, it doesn't matter so much since it's a one-time thing, but solving the environment has so far taken 2 hours on my desktop and it's still going.

**Comment by ajmay81** [comment]
Just to note I installed `mamba` but it was broken, it called out to some shared library that was not installed. Probably they no longer support it standalone as it's now integrated into conda, you just need to one time:
```
conda config --set solver libmamba
```
and then you have something which works reasonably. I think eventually it will become the default.

**Comment by pjknowles** [comment]
yes that's right. Wasn't sure whether `--set solver` had yet made it into conda.
