### ISSUE TITLE
startup errors

### ISSUE THREAD

**Issue by ajmay81** [molpro/iMolpro#32]
Clean python environment installed as per `INSTALL`. 

1. Attempting to start a new project from command line:
```
python Molpro.py project1.molpro
Traceback (most recent call last):
  File "/host/Molpro.py", line 28, in <module>
    window_manager.register(ProjectWindow(arg))
                            ^^^^^^^^^^^^^^^^^^
TypeError: ProjectWindow.__init__() missing 1 required positional argument: 'window_manager'
```
Perhaps this is no longer supported? If not it would be good to trap that in a nicer way.

2. Running with no arguments, select a directory for a new project and gave it a name:
```
python Molpro.py                
Traceback (most recent call last):
  File "/host/Chooser.py", line 152, in newProjectDialog
    self.window_manager.register(ProjectWindow(filename, self.window_manager))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/host/ProjectWindow.py", line 71, in __init__
    os.environ['PATH'] = os.popen(os.environ['SHELL'] + " -l -c 'echo $PATH'").read() + ':' + os.environ[
                                  ~~~~~~~~~~^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'SHELL'
Aborted (core dumped)
```

**Comment by pjknowles** [comment]
> 1. Attempting to start a new project from command line:
> 
> ```
> python Molpro.py project1.molpro
> Traceback (most recent call last):
>   File "/host/Molpro.py", line 28, in <module>
>     window_manager.register(ProjectWindow(arg))
>                             ^^^^^^^^^^^^^^^^^^
> TypeError: ProjectWindow.__init__() missing 1 required positional argument: 'window_manager'
> ```
> 
> Perhaps this is no longer supported? If not it would be good to trap that in a nicer way.

Just not tested following an interface change. Fixed with https://github.com/molpro/QtMolpro/commit/3b9e4ec3cdb849f69931fcf1fe23fb4d76b24f17.

**Comment by pjknowles** [comment]
> 3\. Running with no arguments, select a directory for a new project and gave it a name:
> 
> ```
> python Molpro.py                
> Traceback (most recent call last):
>   File "/host/Chooser.py", line 152, in newProjectDialog
>     self.window_manager.register(ProjectWindow(filename, self.window_manager))
>                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/host/ProjectWindow.py", line 71, in __init__
>     os.environ['PATH'] = os.popen(os.environ['SHELL'] + " -l -c 'echo $PATH'").read() + ':' + os.environ[
>                                   ~~~~~~~~~~^^^^^^^^^
>   File "<frozen os>", line 679, in __getitem__
> KeyError: 'SHELL'
> Aborted (core dumped)
> ```

This is an attempt to get the `PATH` that would be in the user's login shell even if the program is started not from a shell (as on macOS). I had imagined that `SHELL` and `PATH` are always in the environment everywhere, but clearly I am wrong. In any case, it wants doing differently for Windows, and maybe isn't needed in Linux. Another way?
