### ISSUE TITLE
More for Project Menu

### ISSUE THREAD

**Issue by hjwerner** [molpro/iMolpro#43]
show files in a project (ls)
remove files in a project (rm)

**Comment by pjknowles** [comment]
In principle showing the files is already there, simply by using the Export menu, but better to have it explicit.

I suggest instead to do what many IDEs and photo catalogues do, which is to offer "Show in Finder" (or Explorer for windows, or the right thing for linux), and a terminal window. Then the user can do what they want, including renaming.

Note that some renaming - the input file, or the name of any run directory - will break the project integrity - so probably best not to offer it explicitly. Also it's slightly safer to use the clean function to remove old output directories.

**Comment by pjknowles** [comment]
https://github.com/molpro/QtMolpro/pull/44 implements launching of Finder and Terminal on macOS, with equivalents on linux and Windows

**Comment by pjknowles** [comment]
#44 now just implements the simple thing of opening a `QFileDialog` on the project directory, in which inspection, deletion and rename can be done.
