### ISSUE TITLE
geometry window too small

### ISSUE THREAD

**Issue by hjwerner** [molpro/iMolpro#53]
At least on my machine the structure window is too small when displaying an input structure (see first screen shot). One has to extend it to the right to see also the link to the jmol options (second screen shot). This is a bit inconvenient. Also, the jmol option menu appears statistically in different places (submenus as well).

![Bildschirmfoto 2023-10-09 um 12 26 22](https://github.com/molpro/iMolpro/assets/110404565/421de4f9-a2b3-4e98-9e5a-c7459ea1ea3e)
![Bildschirmfoto 2023-10-09 um 12 27 46](https://github.com/molpro/iMolpro/assets/110404565/5ae2f51f-901a-4377-a51c-20de74d9b2f9)

**Comment by pjknowles** [comment]
Yes, agreed, the minimum width of the panel should be changed.

**Comment by hjwerner** [comment]
Perhaps better to move the JMol menu stuff below the input window (right of freehand and guided, or below those).
Currently the input window scales with the whole window size, which may not be needed.

**Comment by pjknowles** [comment]
> Perhaps better to move the JMol menu stuff below the input window (right of freehand and guided, or below those). Currently the input window scales with the whole window size, which may not be needed.

Maybe, and it was once that way, but the way it is presently is dictated by the size needed for seeing the text output. Let's discuss in next meeting.
