### ISSUE TITLE
linked geometry file names not used

### ISSUE THREAD

**Issue by hjwerner** [molpro/iMolpro#54]
When making a link of an xyz file to a different name (just for clarity, e.g. monomer.xyz -> c6h6.xyz) and selecting the link, the original name (monomer.xyz) is used in the input. It's of course not wrong. This happens for example if one has "monomer.xyz" in many different directories for different systems. Certainly not important to fix, unless simple.

**Comment by pjknowles** [comment]
Can you describe more precisely what you are trying to do? A symlink inside the project directory? I hadn't thought about that ever, and some sjef functions such as copy might not work as expected.

**Comment by hjwerner** [comment]
No, a symlink in the directory where the structure is imported from. I had for example in some directory
 pbsbsibigen.xyz -> monomer.xyz <http://monomer.xyz/>

And then imported (using import structure in the file menu) pbsbsibigen.xyz <http://pbsbsibigen.xyz/>. This gave monomer.xyz <http://monomer.xyz/> in the input


Am 09.10.2023 um 12:51 schrieb Peter Knowles ***@***.***>:
