### ISSUE TITLE
Make a guided mode panel that implements only textual input of the `basis` element of the input.

### ISSUE THREAD

**Issue by pjknowles** [molpro/iMolpro#56]
As a first stage, make a guided mode panel that implements only textual input of the `basis` element of the input.

_Originally posted by @pjknowles in https://github.com/molpro/iMolpro/issues/11#issuecomment-1754574107_

**Comment by pjknowles** [comment]
Can be done with `QLineEdit`. The input specification can be obtained as in https://github.com/molpro/iMolpro/blob/feaeda01260592f3b0dbbf8f58a13a60639ca96c/ProjectWindow.py#L257 and then changed.  The input can be rewritten in the `ProjectWindow` class with `self.input_pane.setPlainText(molpro_input.create_input(specification))`. It can just be done in the existing tab that (temporarily) shows the parsed data, ie `self.input_tabs.widget(1)`.

**Comment by pjknowles** [comment]
Getting things done when something has been typed can be achieved like
```
basis_line=QLineEdit()
basis_line.textChanged.connect(my_handler_that_writes_the_input)
```
It does not matter that this would get called for every letter you type - everything is fast enough for this.

**Comment by pjknowles** [comment]
@klauspdoll I have tried to do this in a way that is extensible to other fields, but it probably needs some reflection to see if there is a way to avoid lots of replicated code when other fields are dealt with.

**Comment by klauspdoll** [comment]
This looks excellent, and the code is not too long compared to gtk. Just let me know where to continue, then I could have a go.
