### ISSUE TITLE
freehand mode: cursor jumps to upper left corner when typing

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#64]
in freehand mode, starting from this input:

```
geometry=dummy.xyz
basis={default=cc-pVTZ-PP}
rhf
```

I want to append a line with

`ccsd`

While typing, the cursor often jumps to the upper left part of the window, which is inconvenient; e.g. usually after having typed the first "c" of ccsd, the cursor jumps to the upper left

**Comment by pjknowles** [comment]
Yes, the mutual refreshing of freehand and guided is not quite right yet.
