### ISSUE TITLE
problem with blank in basis={default=cc-pvdz }

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#92]
Version be50a75a25

When I add a blank in this input

```
geometry={
o
h,o,1
}
basis={default=cc-pvdz}
rhf
```

in the line

`basis={default=cc-pvdz }`

before the closing bracket, 
then switch to guided mode is not possible. Doing this change in guided mode gives the error message
`"Guided mode cannot be used because the input is too complex..."`

**Comment by pjknowles** [comment]
Problems like this can usually be diagnosed and fixed relatively straightforwardly. shift-ctrl-g will show a diff of the canonicalised input and the canonicalised input created from the specification.
